version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      typescript-eslint:
        patterns:
        - "@typescript-eslint/*"
      vscode:
        patterns:
        - "@types/vscode"
        - "@vscode/vsce"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
